[workspace]

[package]
name = "display-as-templates"
version = "0.1.0"
authors = ["droundy <roundyd@physics.oregonstate.edu>"]

[dependencies]

display-as = { path = "display-as" }
glob = "0.2.11"
combine = "3.6.2"
regex = "1"
