[package]
name = "display-as"
version = "0.1.0"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]
description = "A trait for displaying data in different markup formats."
repository = "https://github.com/droundy/display-as"
keywords = ["latex", "html", "display"]
license = "Apache-2.0/MIT"

[dependencies]

mime = "0.3.12"

rouille = { version = "1.0", optional = true }
