[package]
name = "display-as"
version = "0.1.5"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]
description = "A trait for displaying data in different markup formats."
repository = "https://github.com/droundy/display-as"
keywords = ["latex", "html", "display"]
license = "Apache-2.0/MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]

mime = "0.3.12"

rouille = { version = "2.2.0", optional = true }
actix-web = { version = "0.7.14", optional = true }
